version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - './dist:/usr/share/nginx/html'
      - './docker-nginx-config.conf:/etc/nginx/conf.d/00-docker.conf'
    ports:
      - '80:80'
